Test on the latest patch versions of supported rubies
everypolitician/close_old_pull_requests pull request #15
Opened 2016-09-30 13:33 UTC by chrismytton

Rather than explicitly specifying a patch version of the rubies we want to test against in `.travis.yml` we can instead just specify major.minor versions and have it automatically test against the latest available patch version.

2016-09-30 13:33 UTC, chrismytton commented
@tmtmtmtm 👀

2016-09-30 18:07 UTC, tmtmtmtm requested changes
not sure if the travis failures might be intermittent, but I've tried rerunning them and it's still failing on 2.3

2016-10-03 09:11 UTC, chrismytton commented
Have just pushed https://github.com/everypolitician/close_old_pull_requests/pull/15/commits/71f038dd0a7281df3a4930709fc2ecbc53420c54 which is more explicit about which version of Ruby 2.3 to use, hopefully that will make Travis green again.

2016-10-06 19:57 UTC, tmtmtmtm approved these changes

2016-10-06 19:57 UTC, merged